# Generated by Django 3.2.11 on 2022-11-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_mop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='mop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.mop'),
        ),
    ]
