# Generated by Django 3.2.11 on 2022-12-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_dailysales_mop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.foodinventory'),
        ),
    ]
