# Generated by Django 3.2.11 on 2023-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_alter_orderprocess_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocess',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
