# Generated by Django 3.2.11 on 2023-05-07 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_alter_orderprocess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocess',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
