# Generated by Django 3.2.11 on 2023-02-26 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_auto_20230226_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffuser',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='is_customer'),
        ),
        migrations.AddField(
            model_name='foodinventory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='foods/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
