# Generated by Django 3.2.11 on 2023-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_orderprocess_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocess',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=25),
            preserve_default=False,
        ),
    ]
