# Generated by Django 3.2.11 on 2023-02-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_auto_20230226_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiffUser',
        ),
    ]
