# Generated by Django 3.2.11 on 2023-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_delete_diffuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysales',
            name='customer',
        ),
    ]
