# Generated by Django 3.2.11 on 2023-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0009_remove_dailysales_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
