# Generated by Django 3.2.11 on 2023-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_alter_dailysales_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
